# many thanks to 
# https://github.com/jakevdp/travis-python-template
# https://github.com/uwescience/shablona

language: python
cache: pip
sudo: false

env:
  global:
    - PACKAGENAME="dms2dfe"
    - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"

python:
  - '2.7'
  
before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDA_URL
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda env create -f environment.yml
- source activate dms2dfe

install:
- python setup.py install --record installed_files.txt

script:
- pytest test/test_configure.py
- pytest test/test_datasets.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: rraadd88
  distributions: sdist bdist_wheel
  password:
    secure: C32wWy9UEGIwWpSVByb0psDnaFDL/xezykSh0wsxQIUqf+psfidowy6vY3+pCwpUIYP655YR0NoipF/KgwftL2qhYfjCXwwDmlxZVQWIL/6jM9XiNkqHD5d/Bm8RTHxvi1Vyw4PSM2QM+1pIgTRr9LWwKlTMv1AR7244pf5v5uZk6MLqcE81Nxf+MmSxtlKZoS8G+4/KskKInxbX3micwk1dfFFGuVDe/JswOZ+yIpmXoBi2CDhBtgvRuTDQ/WiU31SCxde1feLpjZsdRNZKW9vJPUQbtuidgplLBPl9rDZamd+dY9cMJ6nA6Q7JjIivcr1M0ntFuJP52CYtuN+OUhuQt9tUbwLiF7IMsZ23yALJEAIH8G4sCaj+HJTdwps3ChohlXuVCBbJbQi6HMJXXbfgPWifUWkpvqOW0bhVa+/+K9/jIy/II4GJzztbqj0YogKpika/D9lE/b02jNPrSFt0LMs1YwZFjKjncIjVmlNhJ4Cycv3RQWqGpAxxn7crDrx5dsMMJTGulh797CZPCxzg6qKszJ1NYi5M2EYwj4vwRKUwWlKneQdKiT1ZNgAEH4VXtUELIt6M5ugupf6G8s5TSON3Y2UgkE8N81TD9Rv4pWnb2GAGlVCZjUcReXi67FyOO4+3+CUj0VlinX0ne0RZGeUvoEH0lxYVleJbtK8=
  on:
    tags: true
    branch: master